### ISSUE TITLE
C/C++ : Binary Search

### ISSUE THREAD

**Issue by kimpro82** [kimpro82/MyPractice#179]

**Comment by agrasthnaman** [comment]
Pusded a Binary search Code in C.
Merge it if it's needed.

**Comment by kimpro82** [comment]
> Pusded a Binary search Code in C. Merge it if it's needed.

Thank you for your code.
But this repository is for my own study, so I think I should do it by myself.
I hope not break your heart down whatever I don't merge your code.

Have a nice day & take care!
